name: Bump version

on:
  push:
    branches: [ main, stage, devel ]

jobs:
  bump-version0:
    name: Bump version
    runs-on: ubuntu-latest
    if: github.event.head_commit.author.email != 'action@github.com'
    steps:
      - uses: actions/checkout@v2

      - name: Dump GitHub context
        run: |
          echo "$GITHUB_CONTEXT"
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}

      - name: parse-pr-data
        id: parse-pr
        uses: 8BitJonny/gh-get-current-pr@2.1.1

      - name: Print Pr title
        run: echo "PR title ${{steps.parse-pr.outputs.pr_title}}"

      - name: Parse version which version up
        id: which-version
        uses: actions/github-script@v5.0.0
        with:
          result-encoding: string
          script: |
            const prTitle = process.env.PR_TITLE
            const bumpVersion = prTitle.match(/(Major)|(Minor)|(Patch)|(PreMajor)|(PreMinor)|(PrePatch)|(PreRelease)/)
            if (!bumpVersion) {
              return undefined
            }
            const whichVersion = bumpVersion[0].toLocaleLowerCase();

            return whichVersion
        env:
          PR_TITLE: ${{ steps.parse-pr.outputs.pr_title }}

      - name: Print which version
        run: echo "PR title ${{ steps.which-version.outputs.result }}"

      - name: version 업데이트 및 changelog 생성
        if: steps.which-version.outputs.result != 'undefined'
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          npm run release:${{ steps.which-version.outputs.result }}

      - name: 변경내역 푸시
        if: steps.which-version.outputs.result != 'undefined'
        uses: CasperWA/push-protected@v2
        with:
          token: ${{ secrets.PUSH_TO_PROTECTED }}
          branch: ${{ github.ref_name }}
          unprotect_reviews: true
          tags: true
          debug: true
