name: CD

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  print-github-object:
    name: Print github object
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Dump GitHub context
        uses: actions/github-script@v5.0.0
        with:
          script: |
            console.log(process.env.GITHUB_CONTEXT)
            console.log(JSON.stringify(process.env.GITHUB_CONTEXT))
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}

  release-please:
    if: github.event.head_commit.author.email == 'action@github.com'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Dump GitHub context
        run: |
          echo "$GITHUB_CONTEXT"
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}

      - name: Parse current Version
        id: parse-current-version
        uses: juliangruber/read-file-action@v1
        with:
          path: ./package.json

      - name: create release note
        id: created-release
        uses: actions/github-script@v5.0.0
        with:
          result-encoding: string
          script: |
            cosnt parseStagePrefixRegex = /stage/
            const refName = process.env.REF_NAME
            const isPreRelease = refName.match(parseStagePrefixRegex)
            const createdRelease = await github.rest.repos.createRelease({
              owner: context.repo.owner,
              repo: context.repo.repo,
              tag_name: context.ref,
              prerelease: !!isPreRelease,
              generate_release_notes: true,
            })

            return createdRelease.data.html_url
        env:
          REF_NAME: ${{github.ref_name}}

      - name: Parse branch
        id: parse-branch
        uses: actions/github-script@v5.0.0
        with:
          result-encoding: string
          script: |
            cosnt parseStagePrefixRegex = /stage/
            const refName = process.env.REF_NAME
            const isStageBranch = refName.match(parseStagePrefixRegex)

            return !!isStageBranch ? 'stage' : 'prod'
        env:
          REF_NAME: ${{github.ref_name}}

      - name: ChangeLog Slack Alert (Stage)
        if: ${{ steps.parse-branch.outputs.result }} == 'stage'
        uses: actions/github-script@v5.0.0
        with:
          script: |
            console.log('stage branch')

      - name: ChangeLog Slack Alert (prod)
        if: ${{ steps.parse-branch.outputs.result }} == 'prod'
        uses: actions/github-script@v5.0.0
        with:
          script: |
            console.log('main branch')

      - name: print created release
        run: echo "created-release ${{steps.created-release.outputs.result}}"

      - name: parse-pr-data
        id: parse-pr
        uses: 8BitJonny/gh-get-current-pr@2.1.1

      - name: Print Pr title
        run: echo "PR title ${{steps.parse-pr.outputs.pr_title}}"
