name: CD

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  release-please:
    if: github.event.head_commit.author.email == 'action@github.com'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Dump GitHub context
        run: |
          echo "$GITHUB_CONTEXT"
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}

      - name: Parse current Version
        id: parse-current-version
        uses: juliangruber/read-file-action@v1
        with:
          path: ./package.json

      - name: create release note
        id: created-release
        uses: actions/github-script@v5.0.0
        with:
          result-encoding: string
          script: |
            const isPreRelease = String(github.ref_name) === 'stage' ? true : false
            console.log('isPreRelease: ', isPreRelease);
            const createdRelease = await github.rest.repos.createRelease({
              owner: context.repo.owner,
              repo: context.repo.repo,
              tag_name: context.ref,
              prerelease: isPreRelease,
              generate_release_notes: true,
            })

            return createdRelease.data.html_url

      - name: print created release
        run: echo "created-release ${{steps.created-release.outputs.result}}"

      - name: parse-pr-data
        id: parse-pr
        uses: 8BitJonny/gh-get-current-pr@2.1.1

      - name: Print Pr title
        run: echo "PR title ${{steps.parse-pr.outputs.pr_title}}"
