name: CD

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  release-please:
    if: github.event.head_commit.author.email == 'action@github.com'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Parse current Version
        id: parse-current-version
        uses: juliangruber/read-file-action@v1
        with:
          path: ./package.json

      - name: create release note
        id: created-release
        uses: actions/github-script@v5.0.0
        with:
          script: |
            const createdRelease = await github.rest.repos.createRelease({
              owner: context.repo.owner,
              repo: context.repo.repo,
              tag_name: context.ref,
              generate_release_notes: true,
            })

            return createdRelease

      - name: print created release
        run: echo "created-release ${{created-release}}"

      - name: get latest release note
        id: latest-release
        uses: actions/github-script@v5.0.0
        with:
          script: |
            const latestRelease = await github.rest.repos.getLatestRelease({
              owner: context.repo.owner,
              repo: context.repo.repo,
            })

            return latestRelease

      - name: print created release
        run: echo "latest-release ${{latest-release}}"

      - name: parse-pr-data
        id: parse-pr
        uses: 8BitJonny/gh-get-current-pr@2.1.1

      - name: Print Pr title
        run: echo "PR title ${{steps.parse-pr.outputs.pr_title}}"
