name: CI

on:
  pull_request:
    branches: [ main, stage, devel ]

jobs:
  print-github-object:
    name: Print github object
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Dump GitHub context
        uses: actions/github-script@v5.0.0
        with:
          script: |
            console.log(process.env.GITHUB_CONTEXT)
            console.log(JSON.stringify(process.env.GITHUB_CONTEXT))
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}

  CI:
    name: print github object
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Dump GitHub context
        run: |
          echo "$GITHUB_CONTEXT"
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}

      - name: create release note
        id: created-release
        uses: actions/github-script@v5.0.0
        with:
          result-encoding: string
          script: |
            const isPreRelease = github.ref_name === 'devel' ? true : false

            console.log(isPreRelease)
